# Generated by Django 5.1.5 on 2025-02-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='call_to_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
